// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.18.0
// source: wisdom.proto

package wisdom

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Wisdom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value     string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Wisdom) Reset() {
	*x = Wisdom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wisdom_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wisdom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wisdom) ProtoMessage() {}

func (x *Wisdom) ProtoReflect() protoreflect.Message {
	mi := &file_wisdom_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wisdom.ProtoReflect.Descriptor instead.
func (*Wisdom) Descriptor() ([]byte, []int) {
	return file_wisdom_proto_rawDescGZIP(), []int{0}
}

func (x *Wisdom) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Wisdom) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetWisdoms struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetWisdoms) Reset() {
	*x = GetWisdoms{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wisdom_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWisdoms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWisdoms) ProtoMessage() {}

func (x *GetWisdoms) ProtoReflect() protoreflect.Message {
	mi := &file_wisdom_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWisdoms.ProtoReflect.Descriptor instead.
func (*GetWisdoms) Descriptor() ([]byte, []int) {
	return file_wisdom_proto_rawDescGZIP(), []int{1}
}

type GetWisdoms_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetWisdoms_Request) Reset() {
	*x = GetWisdoms_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wisdom_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWisdoms_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWisdoms_Request) ProtoMessage() {}

func (x *GetWisdoms_Request) ProtoReflect() protoreflect.Message {
	mi := &file_wisdom_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWisdoms_Request.ProtoReflect.Descriptor instead.
func (*GetWisdoms_Request) Descriptor() ([]byte, []int) {
	return file_wisdom_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetWisdoms_Request) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetWisdoms_Request) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetWisdoms_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wisdoms []*Wisdom `protobuf:"bytes,1,rep,name=wisdoms,proto3" json:"wisdoms,omitempty"`
}

func (x *GetWisdoms_Response) Reset() {
	*x = GetWisdoms_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wisdom_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWisdoms_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWisdoms_Response) ProtoMessage() {}

func (x *GetWisdoms_Response) ProtoReflect() protoreflect.Message {
	mi := &file_wisdom_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWisdoms_Response.ProtoReflect.Descriptor instead.
func (*GetWisdoms_Response) Descriptor() ([]byte, []int) {
	return file_wisdom_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetWisdoms_Response) GetWisdoms() []*Wisdom {
	if x != nil {
		return x.Wisdoms
	}
	return nil
}

var File_wisdom_proto protoreflect.FileDescriptor

var file_wisdom_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x77, 0x69, 0x73, 0x64, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x77, 0x69, 0x73, 0x64, 0x6f, 0x6d, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x59, 0x0a, 0x06, 0x57, 0x69, 0x73, 0x64, 0x6f, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x94, 0x01, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x57, 0x69, 0x73, 0x64, 0x6f, 0x6d, 0x73, 0x1a, 0x50, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x42, 0x0e, 0xfa, 0x42, 0x04, 0x1a, 0x02, 0x28, 0x01, 0xfa, 0x42, 0x04,
	0x1a, 0x02, 0x18, 0x64, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1f, 0x0a, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x1a, 0x02, 0x28, 0x00, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x1a, 0x34, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x77, 0x69, 0x73, 0x64,
	0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x77, 0x69, 0x73, 0x64,
	0x6f, 0x6d, 0x2e, 0x57, 0x69, 0x73, 0x64, 0x6f, 0x6d, 0x52, 0x07, 0x77, 0x69, 0x73, 0x64, 0x6f,
	0x6d, 0x73, 0x32, 0x52, 0x0a, 0x09, 0x57, 0x69, 0x73, 0x64, 0x6f, 0x6d, 0x53, 0x76, 0x63, 0x12,
	0x45, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x57, 0x69, 0x73, 0x64, 0x6f, 0x6d, 0x73, 0x12, 0x1a, 0x2e,
	0x77, 0x69, 0x73, 0x64, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x69, 0x73, 0x64, 0x6f, 0x6d,
	0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x77, 0x69, 0x73, 0x64,
	0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x69, 0x73, 0x64, 0x6f, 0x6d, 0x73, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x61, 0x72, 0x61, 0x77, 0x61, 0x79, 0x67, 0x67, 0x2f, 0x77,
	0x69, 0x73, 0x64, 0x6f, 0x6d, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x77, 0x69, 0x73, 0x64, 0x6f, 0x6d,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wisdom_proto_rawDescOnce sync.Once
	file_wisdom_proto_rawDescData = file_wisdom_proto_rawDesc
)

func file_wisdom_proto_rawDescGZIP() []byte {
	file_wisdom_proto_rawDescOnce.Do(func() {
		file_wisdom_proto_rawDescData = protoimpl.X.CompressGZIP(file_wisdom_proto_rawDescData)
	})
	return file_wisdom_proto_rawDescData
}

var file_wisdom_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wisdom_proto_goTypes = []interface{}{
	(*Wisdom)(nil),                // 0: wisdom.Wisdom
	(*GetWisdoms)(nil),            // 1: wisdom.GetWisdoms
	(*GetWisdoms_Request)(nil),    // 2: wisdom.GetWisdoms.Request
	(*GetWisdoms_Response)(nil),   // 3: wisdom.GetWisdoms.Response
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_wisdom_proto_depIdxs = []int32{
	4, // 0: wisdom.Wisdom.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: wisdom.GetWisdoms.Response.wisdoms:type_name -> wisdom.Wisdom
	2, // 2: wisdom.WisdomSvc.GetWisdoms:input_type -> wisdom.GetWisdoms.Request
	3, // 3: wisdom.WisdomSvc.GetWisdoms:output_type -> wisdom.GetWisdoms.Response
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wisdom_proto_init() }
func file_wisdom_proto_init() {
	if File_wisdom_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wisdom_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Wisdom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wisdom_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWisdoms); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wisdom_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWisdoms_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wisdom_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWisdoms_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wisdom_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wisdom_proto_goTypes,
		DependencyIndexes: file_wisdom_proto_depIdxs,
		MessageInfos:      file_wisdom_proto_msgTypes,
	}.Build()
	File_wisdom_proto = out.File
	file_wisdom_proto_rawDesc = nil
	file_wisdom_proto_goTypes = nil
	file_wisdom_proto_depIdxs = nil
}
